app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    # path('prediction/', views.prediction, name='prediction')
]

diabetes/urls.py
from django.urls import path
from . import views
app_name = 'diabetes'

urlpatterns = [
    path('', views.diabetes, name='diabetes')
]

pizza/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('diabetes/', include('diabetes.urls')),
]

app/models.py
from django.db import models

# Create your models here.

diabetes/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import redirect, render
import pandas as pd
import json
# Create your views here.

def linear_regression(value=0):
    data_set = pd.read_csv('dataset.csv')

    population = data_set['population']
    sales = data_set['sales']

    population_mean = population.mean()
    sales_mean = sales.mean()

    population_sum = population[:] - population_mean
    sales_sum = sales[:] - sales_mean

    m = (population_sum * sales_sum).sum() / (population_sum ** 2).sum()
    c = sales_mean - (m * population_mean)

    return {
        'regression': m * value + c,
        'population': population,
        'sales': sales,
        'data_set': data_set
    }


def index(request):
    context = dict()

    if request.method == 'GET':
        regression = linear_regression()
        data_set = dict(regression['data_set'].values)

        datas = list()
        for key, data in data_set.items():
            datas.append({
                'x': key,
                'y': data
            })

        context['regression'] = json.dumps({})
        context['data'] = json.dumps(datas)
        context['result'] = 0

        return render(request, 'app/index.html', context)
    elif request.method == 'POST':
        context = dict()

        population = float(request.POST['population'])
        regression = linear_regression(population)
        data_set = dict(regression['data_set'].values)

        datas = list()
        for key, data in data_set.items():
            datas.append({
                'x': key,
                'y': data
            })

        context['data'] = json.dumps(datas)
        
        result = regression['regression']
        context['regression'] = json.dumps({
            'x': population,
            'y': result
        })
        context['result'] = result

        return render(request, 'app/index.html', context)

diabetes/views.py
from numpy.core.records import array
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from django.shortcuts import render, redirect

# Create your views here.

def diabetes(request):
    context = dict()

    if request.method == 'POST':
        glucose = int(request.POST['glucose_name'])
        blood_pressure = int(request.POST['blood_pressure_name'])
        insulin = int(request.POST['insulin_name'])
        pedigree = float(request.POST['pedigree_name'])

        data_set = pd.read_csv('diabetes.csv')

        x = np.array(data_set[['Glucose', 'BloodPressure', 'Insulin', 'DiabetesPedigreeFunction']])
        y = np.array(data_set['Outcome'])

        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.33, random_state=42)
        model = LogisticRegression()
        model.fit(x_train, y_train)

        y_predict = model.predict([[glucose, blood_pressure, insulin, pedigree]])

        probability = model.predict_proba([[glucose, blood_pressure, insulin, pedigree]])

        if y_predict[0]:
            context['diabetes'] = 'Diabetic!'
        else:
            context['diabetes'] = 'Not Diabetic!'

        context['positive'] = round(probability[0][1] * 100, 2)
        context['negative'] = round(probability[0][0] * 100, 2)

        return render(request, 'diabetes/index.html', context)
    else:
        context['diabetes'] = 'Not Diabetic!'
        context['positive'] = 0
        context['negative'] = 0
        return render(request, 'diabetes/index.html', context)

app/templates/app/base.html
{% load bootstrap5 %}
{% load static %}

<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}

        {% block default_script %}
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        {% endblock default_script %}
        
        {% block css %}{% endblock css %}
    </head>
    <body>
        <nav class="navbar navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'app:index' %}">Pizza Prediction</a>
            </div>
        </nav>
        <main class="container">
            {% block content %}

            {% endblock content %}
        </main>
    </body>
    {% block script %}{% endblock script %}
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <form method="POST" action="{% url 'app:index' %}">
        {% csrf_token %}
        <input 
            class="form-control form-control-lg mt-3" 
            type="number" 
            placeholder="Population" 
            name="population"
            step="any"
            required
        >
        <div class="d-grid gap-2">
            <button class="btn btn-primary btn-lg mt-3" type="submit">Submit</button>
        </div>
    </form>

    <h1>Sales: {{ result }}</h1>
    <div class="container text-center">
        <canvas id="myChart" width="1000" height="350"></canvas>
    </div>
{% endblock %}
{% block script %}
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var datas = JSON.parse("{{ data }}".replace(/&quot;/g,'"'));
        var regression =JSON.parse("{{ regression }}".replace(/&quot;/g,'"'));

        var myChart = new Chart(ctx, {
            type: 'scatter',
            data: {
                labels: ['Pizza', 'Sales'],
                datasets: [
                    {
                        label: 'Pizza Sales',
                        data: datas,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1,
                        pointRadius: 10,
                    },
                    {
                        label: 'User Input',
                        data: [regression],
                        backgroundColor: [
                            'rgba(54, 162, 235, 0.2)',
                        ],
                        borderColor: [
                            'rgba(54, 162, 235, 1)',
                        ],
                        borderWidth: 1,
                        pointRadius: 20,
                    },
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                scales: {
                    x: {
                        type: 'linear',
                        position: 'bottom',
                    },
                },
            }
        });
    </script>
{% endblock script %}

app/templates/app/prediction.html
{% extends 'app/base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <form method="POST" action="{% url 'app:prediction' %}">
        {% csrf_token %}
        <input 
            class="form-control form-control-lg mt-3" 
            type="number" 
            placeholder="Population" 
            name="population"
            step="any"
            required
        >
        <div class="d-grid gap-2">
            <button class="btn btn-primary btn-lg mt-3" type="submit">Submit</button>
        </div>
    </form>

    <h1>Sales: {{ result }}</h1>
    <div class="container text-center">
        <canvas id="myChart" width="1000" height="350"></canvas>
    </div>
    
    
{% endblock %}
{% block script %}
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var datas = JSON.parse("{{ data }}".replace(/&quot;/g,'"'));
        var regression =JSON.parse("{{ regression }}".replace(/&quot;/g,'"'));

        console.log(regression)

        var myChart = new Chart(ctx, {
            type: 'scatter',
            data: {
                labels: ['Population', 'Sales'],
                datasets: [
                    {
                        label: 'Prediction Sales',
                        data: datas,
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(255, 206, 86, 0.2)',
                            'rgba(75, 192, 192, 0.2)',
                            'rgba(153, 102, 255, 0.2)',
                            'rgba(255, 159, 64, 0.2)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(255, 206, 86, 1)',
                            'rgba(75, 192, 192, 1)',
                            'rgba(153, 102, 255, 1)',
                            'rgba(255, 159, 64, 1)'
                        ],
                        borderWidth: 1,
                        pointRadius: 10,
                    },
                    {
                        label: 'User Input',
                        data: [regression],
                        backgroundColor: [
                            'rgba(54, 162, 235, 0.2)',
                        ],
                        borderColor: [
                            'rgba(54, 162, 235, 1)',
                        ],
                        borderWidth: 1,
                        pointRadius: 20,
                    },
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                scales: {
                    x: {
                        type: 'linear',
                        position: 'bottom'
                    }
                },

            }
        });
    </script>
{% endblock script %}

diabetes/templates/diabetes/base.html
{% load bootstrap5 %}
{% load static %}

<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}

        {% block default_script %}
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        {% endblock default_script %}
        
        {% block css %}{% endblock css %}
    </head>
    <body>
        <nav class="navbar navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'diabetes:diabetes' %}">Diabetes Logistic Regression</a>
            </div>
        </nav>
        <main class="container">
            {% block content %}

            {% endblock content %}
        </main>
    </body>
    {% block script %}{% endblock script %}
</html>

diabetes/templates/diabetes/index.html
{% extends 'diabetes/base.html' %}

{% block title %}Home{% endblock title %}
{% block content %}
<form method="POST" action="{% url 'diabetes:diabetes' %}">
    {% csrf_token %}
    <div class="row mt-3">
        <div class="col">
            <div class="row">
                <label for="glucose" class="form-label">Glucose</label>
            </div>
            <input name="glucose_name" style="width: 600px" type="range" value="0" min="0" max="199" oninput="glucose.value = this.value">
            <output id="glucose">0</output>
        </div>
        
        <div class="col">
            <div class="row">
                <label for="blood_pressure" class="form-label">Blood Pressure</label>
            </div>
            <input name="blood_pressure_name" style="width: 600px" type="range" value="0" min="0" max="122" oninput="blood_pressure.value = this.value">
            <output id="blood_pressure">0</output>
        </div>

        <div class="col mt-4">
            <div class="row">
                <label for="insulin" class="form-label">Insulin</label>
            </div>
            <input name="insulin_name" style="width: 600px" type="range" value="0" min="0" max="846" oninput="insulin.value = this.value">
            <output id="insulin">0</output>
        </div>

        <div class="col mt-4">
            <div class="row">
                <label for="pedigree" class="form-label">Diabetes Pedigree Function</label>
            </div>
            <input name="pedigree_name" style="width: 600px" type="range" value="0" min="0" step="0.1" max="3" oninput="pedigree.value = this.value">
            <output id="pedigree">0</output>
        </div>
    </div>
    <button class="btn btn-primary mt-3">Submit</button>
</form>
<div class="text-center">
    <h1>{{ diabetes }}</h1>
    <h1>{{ positive }}% of having a diabetes.</h1>
    <h1>{{ negative }}% of not having a diabetes.</h1>
</div>
{% endblock content %}